

data_details : 
  raw : "./data/jsb_chorales/all"
  out : "./data/jsb_chorales/processed"
  version: "version_1_seq_256"
  seq_length: 16

epochs: 40
rnn_units : 256
embedding_dim: 16
vocab_size: 13 # 12 notes and a rest

run_name : "v3_multimodels_256_40epoch"
do_training: True
