

data_details : 
  # raw : "./data/jsb_chorales/all"
  raw : "./data/jsb_chorales/jsb16thSeparated.json"
  out : "./data/jsb_chorales/processed"
  version: "version_4_16th_notes_transposed_seq_128_octaved" # used to be 8th
  seq_length: 128
  token_empty_note: 12 # change this back
  token_reset_song: 13

epochs: 130
rnn_units : 512
embedding_dim: 32
vocab_size: 14  # 12 notes + reset token(12)  reset song token is always incorrect + no-note(13)

run_name : "v12_16th_notes_seq_128_transposed_octaved" # v5_8th_notes_seq_32_transposed was goood
do_training: True
