

data_details : 
  raw : "./data/jsb_chorales/all"
  out : "./data/jsb_chorales/processed"
  version: "version_1_tfdata_seq_256_easy_timesig"
  seq_length: 128

epochs: 100
rnn_units : 512
embedding_dim: 32
vocab_size: 14 # 12 notes + start token + end token

run_name : "v2_single_model_3_GRUs"
do_training: True
