

data_details : 
  raw : "./data/jsb_chorales/all"
  out : "./data/jsb_chorales/processed"
  version: "version_1_seq_256"
  seq_length: 16

epochs: 20
rnn_units : 256
embedding_dim: 16
vocab_size: 13 # 12 notes and a rest

run_name : "base_model_dev_seq_256"
checkpoint_root : './training_checkpoints'
do_training: True
